### ISSUE TITLE
Can only build with a single version of OS X SDK/Xcode

### ISSUE THREAD

**Issue by mrtom** [atom/brightray#144]
I'm trying to build brightray as part of electron. I'm getting the following error:

`xcodebuild: error: SDK "macosx10.10" cannot be located.`

Output of -showsdks:
```
xcodebuild -showsdks
OS X SDKs:
	OS X 10.11                    	-sdk macosx10.11

iOS SDKs:
	iOS 9.0                       	-sdk iphoneos9.0

iOS Simulator SDKs:
	Simulator - iOS 9.0           	-sdk iphonesimulator9.0

watchOS SDKs:
	watchOS 2.0                   	-sdk watchos2.0

watchOS Simulator SDKs:
	Simulator - watchOS 2.0       	-sdk watchsimulator2.0
```

This is, I suspect, because I've updated to Xcode 7 (which comes with SDK for 10.11), but I'm still running OS X Yosemite (as El Cap isn't out yet).

Any ideas how to manually set the SDK version to 10.11?

**Comment by joshaber** [comment]
It looks like the SDK is set in `brightray.gypi`: https://github.com/atom/brightray/blob/25f3a9d0a5b73ec170a65f4e2e4c9ad91e23fc8c/brightray.gypi#L36

**Comment by mrtom** [comment]
Thanks for the quick response @joshaber - that's fixed it (tho temporarily I suppose)

**Comment by mrtom** [comment]
FWIW, before changing the value as @joshaber suggested, I tried updating to El Capitan GM, but had the same issue (obviously, seeing as the value is hardcoded). 

Might be worth updating the script to a required minimum or advisable version, and querying for the currently installed versions so you can choose an appropriate version at runtime. Otherwise this is going to happen every time a new Xcode seed comes out.

I'll leave this task open (and update the title) to track that issue.
