### ISSUE TITLE
Windows Notifications

### ISSUE THREAD

**Issue by felixrieseberg** [atom/brightray#163]
We have a cuddly little PR over in #161 and already made decent progress. Here's what's left to do:

- [x] Set the body/text of the toast message
- [x] Set image of the toast
- [x] Verify multiple templates
- [x] Handle callbacks
- [x] Document the shortcut requirement on Windows 8
- [x] Handle `close()`

Re: [Electron Issue #262](https://github.com/atom/electron/issues/262)

**Comment by jpoon** [comment]
As for the Win8 shortcut requirement, IMO installing a shortcut doesn't belong here as the electron app should be responsible for creating a start menu shortcut when it first gets installed. Found legit looking code (from [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802762(v=vs.85).aspx)) to check for a shortcut (and, install it if we go that route).

**Comment by paulcbetts** [comment]
:-1: on creating shortcuts automatically as well

**Comment by felixrieseberg** [comment]
Seems solid, I'll take it out. Thanks for the feedback!

**Comment by felixrieseberg** [comment]
Images are now working :fireworks:

**Comment by felixrieseberg** [comment]
Callbacks are working, too :fire:

**Comment by paulcbetts** [comment]
If you ignored `close` you'd probably be fine, I believe Linux does the same

**Comment by felixrieseberg** [comment]
@jpoon just wanted a few hours to bang his head against it - but I agree, getting what we have right now in would already be awesome.

@paulcbetts would you mind taking a short look if you agree with the stuff we did here? I'd :heart: if you could take a peek.

**Comment by jpoon** [comment]
Hide/Close is now implemented.

**Comment by jpoon** [comment]
For the shortcut requirement, I'm curious if that is actually the case. According to [MSDN](https://msdn.microsoft.com/library/windows/apps/windows.ui.notifications.toastnotificationmanager.aspx) in order to send a toast, we need: 

* For a desktop app to display a toast, the app must have a shortcut on the Start screen.
* The shortcut must have an AppUserModelID.

On Win10, I had neither and was still able to send a toast. I have a gut feeling that the documentation may be out-of-date and the shortcut is not necessary for Win8. I'll spin up a VM tomorrow and report my findings.

**Comment by zcbenz** [comment]
> On Win10, I had neither and was still able to send a toast. I have a gut feeling that the documentation may be out-of-date and the shortcut is not necessary for Win8. I'll spin up a VM tomorrow and report my findings.

It is probably changed on Windows 10, on my Windows 8 machine I have to create a shortcut in start screen with an AppUserModelID to be able to send toast notification.

**Comment by miniak** [comment]
In the current state the code is not going to run on Windows 7. You are linking `WindowsCreateString`, `WindowsDeleteString`, `RoGetActivationFactory` and `RoInitialize` statically. It has to be loaded dynamically using `LoadLibrary` / `GetProcAddress`. I have commented on that already in https://github.com/atom/brightray/pull/161.

**Comment by miniak** [comment]
Also I would suggest using the `DesktopToastFailedEventHandler` to raise https://developer.mozilla.org/en-US/docs/Web/API/Notification/onerror. Currently, when you pass a http/https icon URL, the notification does not display on Windows 8 and the DesktopToastFailedEventHandler gets triggered.

**Comment by miniak** [comment]
https://github.com/atom/brightray/pull/170

**Comment by jpoon** [comment]
Super appreciate all the feedback @miniak. We'll get another PR out there shortly to address Win7 and below.

**Comment by felixrieseberg** [comment]
@miniak: LoadLibrary is a little bit outdated, I just used DelayLoad (it's used throughout Brightray already). I really appreciate your checks though, we can always use additional :eyes:.

Merged in #172

**Comment by miniak** [comment]
@felixrieseberg I didn't notice that you are using delayload. That's definitely more elegant. In this case the whole DLL is unavailable on Win7. You can only use it per library, not per symbol, am I right?

**Comment by felixrieseberg** [comment]
Yeah, it does [have a few constraints](https://msdn.microsoft.com/en-us/library/yx1x886y.aspx).

I'll close this issue for now - we have the work sketched out here done (except for the excellent addition of the `DesktopToastFailedEventHandler`, which @miniak already kindly made a PR for).
